[project]
name = "meetings-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "cookiecutter>=2.6.0",
    "django>=4.2.23",
    "django-cotton>=2.1.3",
    "django-environ>=0.11.2",
    "django-tailwind>=3.4.0",
]
